export const REQUEST_TODOLISTS = 'REQUEST_TODOLISTS'
export const ADD_TODOLIST = 'ADD_TODOLIST'
export const UPDATE_TODOLIST = 'UPDATE_TODOLIST'
export const DELETE_TODOLIST = 'DELETE_TODOLIST'

export const REQUEST_TODOS = 'REQUEST_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'